
# Dev mode enabled?
dev_mode: false

# Terminal title
terminal_title: "ChicknTurtle's Bots"

# Should debug messages be shown in log?
log_debug: false

# Time between each autosave (seconds)
autosave_time: 60

# Channels
channels:
  system: 991049580634308688
  log: 991110356908908704
  feedback: 1243661131961077861

# Other ids
dev_guild: 985362099490390096

# Modules for each bot

ext_tuttlebot:
  - events
  - help
  - bot

ext_neoturtle:
  - events
  - help
  - bot

ext_splatdrone:
  - events
  - help
  - bot
